### PR TITLE
Ensure that deployment fails when enable_health_check_http: true and there are no healthy backends

### LINKED ISSUE #195: Initial deployment succeeds when `enable_health_check_http: true` even when there are no healthy backends
### Background:
`enable_health_check_http: true` Enables the HAProxy health check endpoint which reports the health of the backends. It also adds a monit `check host` service check which checks this health endpoint and causes BOSH to report the deployment as failing when HAProxy has no healthy backends.

### Expected behaviour: 
When deploying HAProxy with `enable_health_check_http: true` and there are no healthy backends, the deployment should fail

### Actual behaviour: 
When deploying HAProxy with `enable_health_check_http: true` and there are no healthy backends, the deployment succeeds and exits with a zero exit code,  but about five seconds later `bosh instances` correctly reports the deployment as failing

### PR DESCRIPTION
**Pull request by peterellisjones**
Fixes #195 

Requires https://github.com/cloudfoundry-incubator/haproxy-boshrelease/pull/192 is merged first

With this change deployments with unhealthy backends will fail with:

```
Task 6 | 12:30:42 | L starting jobs: haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0) (canary) (00:00:40)
                  L Error: 'haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0)' is not running after update. Review logs for failed jobs: haproxy-health
Task 6 | 12:31:14 | Error: 'haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0)' is not running after update. Review logs for failed jobs: haproxy-health
```

### CODE REVIEW

File: acceptance-tests/bosh_helpers.go [hunk 1]
```diff
@@ -19,14 +19,27 @@ type haproxyInfo struct {
...
+type baseManifestVars struct {
+	haproxyBackendPort    int
+	haproxyBackendServers []string
+	deploymentName        string
+}
+
 type varsStoreReader func(interface{}) error
 
 // Helper method for deploying HAProxy
 // Takes the HAProxy backend port, an array of custom opsfiles, a map of custom vars
```
Comment (domdom82) [inline acceptance-tests/bosh_helpers.go:31]: comment no longer matches arguments

File: acceptance-tests/bosh_helpers.go [hunk 2]
```diff
@@ -123,7 +142,7 @@ func dumpHAProxyConfig(haproxyInfo haproxyInfo) {
 
 // Takes bosh deploy ops files and vars.
```
Comment (domdom82) [inline acceptance-tests/bosh_helpers.go:143]: comment outdated

File: acceptance-tests/bosh_helpers.go [hunk 3]
```diff
@@ -234,9 +253,9 @@ func boshInstances() []boshInstance {
 	return output.Tables[0].Rows
 }
 
-func deleteDeployment() {
+func deleteDeployment(boshDeployment string) {
 	By("Deleting the HAProxy deployment")
```
Comment (domdom82) [inline acceptance-tests/bosh_helpers.go:257]: can we print the `boshDeployment` string here? maybe helps in debugging later

File: acceptance-tests/bosh_helpers.go [hunk 4]
```diff
@@ -123,7 +142,7 @@ func dumpHAProxyConfig(haproxyInfo haproxyInfo) {
 
 // Takes bosh deploy ops files and vars.
 // Returns a session object and a callback to deserialise the bosh-generated vars store after session has executed
-func deployBaseManifest(opsFilesContents []string, vars map[string]interface{}) (*gexec.Session, varsStoreReader) {
+func deployBaseManifest(boshDeployment string, opsFilesContents []string, vars map[string]interface{}) (*gexec.Session, varsStoreReader) {
 	By("Deploying HAProxy")
```
Comment (domdom82) [inline acceptance-tests/bosh_helpers.go:146]: can we print the `boshDeployment` string here? maybe helps in debugging later

**Review by domdom82 — CHANGES_REQUESTED** [review]

File: acceptance-tests/bosh_helpers.go (hunk 1 above)
Comment (peterellisjones) [reply acceptance-tests/bosh_helpers.go]: Fixed

File: acceptance-tests/bosh_helpers.go (hunk 2 above)
Comment (peterellisjones) [reply acceptance-tests/bosh_helpers.go]: Fixed

File: acceptance-tests/bosh_helpers.go (hunk 4 above)
Comment (peterellisjones) [reply acceptance-tests/bosh_helpers.go]: Fixed

File: acceptance-tests/bosh_helpers.go (hunk 3 above)
Comment (peterellisjones) [reply acceptance-tests/bosh_helpers.go]: Fixed

**Review by domdom82 — APPROVED** [review]
